project:
  type: book
  preview:
    port: 4201
    browser: true
book:
  title: "Ollama Notları"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: ollama-logo.png
  chapters:
    - index.qmd
    - intro.qmd
    - ollama-modeller.qmd
    - ollama-uygulamalar.qmd
    - ollama-cli.qmd
    - ollama-UI-ornekler.qmd
    - ollama-json-api.qmd
    - prompting.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



