# Ollama JSON API Powershell

Ollama serve komutu ile arkaplan hizmeti başlatıyoruz.

```powershell
ollama serve
```

Başka bir pencerede veya tab'ta powershell açalım.
Aşağıdaki komut ile ollama'nın çalıştığını kontrol edelim.

```powershell
Invoke-WebRequest http://localhost:11434/
```

Ollama çağrılarını yaparken json nesneleri kullanıyoruz.
En basit çağrımızda model ve süfle (prompt) değerlerini vermemiz gerekir.


```json
{
"model": "ds15", 
"prompt": "What is your name?" 
} 
```

Aşağıdaki komut ile yukarıdaki json nesnesi ile bir çağrı yapabiliriz.

```powershell
Invoke-WebRequest -method POST -Body '{"model":"ds15", "prompt":"What is your name?"}' -uri http://localhost:11434/api/generate 
```

Ama bunun sonucu çok anlamlı olmayacaktır.

```powershell
{{< include komut-sonuclari/powershell-invoke-request-simple.txt >}}
```

Bizim bu isteğe gelen cevabın içeriğini (Content) almamız gerekiyor.
Arkasından bunu json'dan çevirelim.
Sonucu akış değil bir defada almak için ayrıca stream false değerinide gönderelim.



```powershell
(Invoke-WebRequest -method POST -Body '{"model":"ds15", "prompt":"What is your name?", "stream": false}' -uri http://localhost:11434/api/generate ).Content | ConvertFrom-json
```

Cevabımız aşağıdaki gibi olacaktır.
Sizin aldığınız cevap, büyük dil modellerini olasıksal çalışması yüzünden, bundan farklı olabilir.

```powershell
{{< include komut-sonuclari/powershell-invoke-request-simple-answer.txt >}}
```


